services:
  main:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    working_dir: /usr/app/src
    volumes:
      - ./app:/usr/app/src
